name: Deploy and Trigger on Version Change

on:
  push:
    branches: [main]

jobs:
  read-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read versions from file
        id: get-versions
        run: |
          echo "Reading versions from versions.json"
          matrix=$(jq -c 'to_entries | map({service: .key, version: .value})' versions.json)
          echo "::set-output name=matrix::$matrix"

      - name: Log matrix
        id: log-matrix
        run: |
          echo "Matrix: :${{ steps.get-versions.outputs.matrix }}"

  detect-version-change:
    needs: read-versions
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        service_version: ${{ fromJson(needs.read-versions.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-depth: 0

      - name: Get previous commit hash
        id: previous_commit
        run: |
          previous_commit_hash=$(git log --pretty=format:%H -n 2 | tail -n 1)
          echo "::set-output name=commit_hash::${previous_commit_hash}"

      - name: Get current version
        id: current_versions
        run: |
          current_version=$(jq -c --arg service "${{ matrix.service_version.service }}" '.[$service]' versions.json)
          echo "::set-output name=current_version::${current_version}"

      - name: Get previous version
        id: previous_versions
        run: |   
          previous_version=$(git show ${{ steps.previous_commit.outputs.commit_hash }}:versions.json | jq -c --arg service "${{ matrix.service_version.service }}" '.[$service]')
          echo "::set-output name=previous_version::${previous_version}"

      - name: Check for version changes
        id: version_check
        run: |
          current_version="${{ steps.current_versions.outputs.current_version }}"
          previous_version="${{ steps.previous_versions.outputs.previous_version }}"

          echo "Current Version: $current_version"
          echo "Previous Version: $previous_version"
          
          if [[ "$current_version" != "$previous_version" ]]; then
            echo "${{ matrix.service_version.service }}" >> changed_services.txt
          fi

      - name: Upload changed services file
        uses: actions/upload-artifact@v2
        with:
          name: changed_services
          path: changed_services.txt

  process-versions:
    needs: detect-version-change
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download changed services file
        uses: actions/download-artifact@v2
        with:
          name: changed_services
          path: .

      - name: Process each changed service
        id: process-services
        run: |
          changed_services=$(jq -R -s -c 'split("\n")[:-1]' changed_services.txt)
          echo "Changed Services: $changed_services"
          echo "::set-output name=changed_services::$changed_services"

      - name: Loop through services and trigger workflows
        run: |
          changed_services=$(jq -r '.[]' <<< "${{ steps.process-services.outputs.changed_services }}")
          for service in $changed_services; do
            echo "Triggering workflow for service: $service"
            current_version=$(jq -r --arg service "$service" '.[$service]' versions.json)

            gh workflow run -f env="preprod" -f tag_version="$current_version"
          done
