name: Trigger workflow in another repository with branch
run-name: ${{ github.actor }} triggered workflow with branch in another repository

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: build
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Extract branch name # Extract the branch name for the deployment environment
        shell: bash
        run: |
          echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Trigger workflow in the traser repository
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: branch_dispatch.yml
          repo: soringumeni1/multiple-env-poc
          ref: |-
              ${{
                github.ref_name == 'dev' && 'dev'
              || github.base_ref == 'dev' && 'dev'
              ||                             'main'
              }}
          inputs: |
            {
              "env": "${{ steps.extract_branch.outputs.branch }}"
            }
          token: ${{ secrets.MY_TOKEN }}
