name: Run Actions for Each Version

on:
  workflow_dispatch:

jobs:
  read-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read versions from file
        id: get-versions
        run: |
          matrix=$(jq -r 'to_entries | map({ service: .key, version: .value })' versions.json)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

      - name: Set matrix
        id: set-matrix
        run: echo "::set-output name=matrix::${{ steps.get-versions.outputs.matrix }}"

  process-versions:
    needs: read-versions
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.read-versions.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo Version
        run: echo "Processing ${{ matrix.service }} version ${{ matrix.version }}"

      # Add your action step here
      - name: Example Action
        run: |
          echo  ${{ matrix.service }}
          echo  ${{ matrix.version }}
