name: Run Actions for Each Version

on:
  workflow_dispatch:

jobs:
  process-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read versions from file
        id: get-versions
        run: |
          echo "Creating a matrix from versions.json"
          matrix=$(jq -c 'to_entries | map({service: .key, version: .value})' versions.json)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  run-actions:
    needs: process-versions
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ needs.process-versions.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo Version
        run: echo "Processing ${{ matrix.service }} version ${{ matrix.version }}"

      # Add your action step here
      - name: Example Action
        run: |
          echo ${{ matrix.service }}
          echo ${{ matrix.version }}
