name: Run Actions for Each Version

on:
  push:
    branches:
      - "main"

jobs:
  read-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-versions.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read versions from file
        id: get-versions
        run: |
          echo "Reading versions from versions.json"
          matrix=$(jq -c 'to_entries | map({service: .key, version: .value})' versions.json)
          echo "::set-output name=matrix::$matrix"

      - name: Log Matrix Before Set-Output
        run: |
           echo "Matrix before set-output: ${{ steps.get-versions.outputs.matrix }}"

  process-versions:
    needs: read-versions
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.read-versions.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log Matrix in process-versions
        run: |
          echo "Matrix in process-versions: ${{ fromJson(needs.read-versions.outputs.matrix) }}"

      - name: Echo Version
        run: echo "Processing ${{ matrix.service }} version ${{ matrix.version }}"

      - name: Example Action
        run: |
          echo ${{ matrix.service }}
          echo ${{ matrix.version }}
